import type { Product } from "@/lib/types"

const brandedSmartphones: Product[] = [
  {
    id: "smartphone-iphone-17",
    name: "iPhone 17",
    category: "Smartphones",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-compare-iphone-17-202509?.v=M0dlUVBobHVpY1h1dmlaR3RZekpENGh0eTVTNkN2NWpWZVAwbzMwQlBCTkxxZU5scXpES1hnUm96ckN1R2pZN215d1FhSDJ0bkR0ZGZtUjZJNmFveFo2eWNJSlJFRDM1UWQ2eUozZ1l5ZDA&fmt=png-alpha&hei=512&wid=400",
    price: 799,
    rating: 4.7,
    reviewCount: 1118,
    processor: "A19",
    ram: "8GB",
    ramGb: 8,
    storage: "256GB",
    storageGb: 256,
    display: '6.3" Super Retina XDR',
    battery: "Up to 29 hours video playback",
    batteryScore: 88,
    performance: "Premium everyday flagship",
    performanceScore: 91,
    camera: "48MP + 12MP dual camera",
    weight: "173g",
    weightGrams: 173,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best iPhone Value",
    pros: ["Excellent performance efficiency", "Reliable cameras for daily use", "Long software support"],
    cons: ["Still pricey compared with Android rivals", "Charging remains slower than some competitors"],
    summary: "A balanced iPhone with refined battery life, polished software, and strong all-around usability.",
    imageLabel: "Official Apple product image",
    tags: ["iphone", "apple", "ios", "value"],
    featured: true,
  },
  {
    id: "smartphone-iphone-air",
    name: "iPhone Air",
    category: "Smartphones",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-compare-iphone-air-202509?.v=M0dlUVBobHVpY1h1dmlaR3RZekpEMGtrRFZUNExaR0FUNGxJZXJuT2lqUjE5VXk1QVF5NWxrMFlTNWNpV2huNVM0TjRWdzF2UjRGVEY0c3dBQVZ6VGUza2N1YW5ubjVFaHZuNzNKcFIzTnc&fmt=png-alpha&hei=512&wid=400",
    price: 999,
    rating: 4.6,
    reviewCount: 824,
    processor: "A19 Pro",
    ram: "12GB",
    ramGb: 12,
    storage: "256GB",
    storageGb: 256,
    display: '6.5" Super Retina XDR ProMotion',
    battery: "Up to 27 hours video playback",
    batteryScore: 84,
    performance: "Slim premium flagship",
    performanceScore: 95,
    camera: "48MP Fusion main camera",
    weight: "162g",
    weightGrams: 162,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Lightweight Premium",
    pros: ["Very light and thin for its class", "Fast flagship chip", "Premium materials and feel"],
    cons: ["Single rear camera limits flexibility", "Higher price for the design-first focus"],
    summary: "A design-led iPhone built for buyers who want a lighter flagship without dropping into the base tier.",
    imageLabel: "Official Apple product image",
    tags: ["iphone", "apple", "lightweight", "premium"],
  },
  {
    id: "smartphone-iphone-17-pro",
    name: "iPhone 17 Pro",
    category: "Smartphones",
    imageUrl:
      "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-compare-iphone-17-pro-202509?.v=M0dlUVBobHVpY1h1dmlaR3RZekpEMi9sbCsxVVJmYjNiS29STjQrZEV5NnNlL1VpWDFHcHBMQXVUWWdWdkZZNGJPbDJJWDFrVGJEYlIxTitTcHhVWldNTk4rSDJkMy8vL20va2hrM1NheXZ4VldteDRHenNWeThpV3EzUWVVd2o&fmt=png-alpha&hei=512&wid=400",
    price: 1099,
    rating: 4.9,
    reviewCount: 946,
    processor: "A19 Pro",
    ram: "12GB",
    ramGb: 12,
    storage: "512GB",
    storageGb: 512,
    display: '6.3" Super Retina XDR ProMotion',
    battery: "Up to 39 hours video playback",
    batteryScore: 96,
    performance: "Pro-tier flagship",
    performanceScore: 99,
    camera: "48MP + 48MP + 48MP Pro camera system",
    weight: "199g",
    weightGrams: 199,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best for Creators",
    pros: ["Excellent battery endurance", "Versatile camera system", "Top-end sustained performance"],
    cons: ["Premium pricing", "Accessories and storage upgrades add up fast"],
    summary: "A high-end iPhone focused on camera flexibility, performance, and premium build quality.",
    imageLabel: "Official Apple product image",
    tags: ["iphone", "apple", "pro", "camera"],
    featured: true,
  },
  {
    id: "smartphone-galaxy-s25",
    name: "Samsung Galaxy S25",
    category: "Smartphones",
    imageUrl:
      "https://image-us.samsung.com/us/smartphones/galaxy-s25/images/galaxy-s25-features-kv.jpg",
    price: 799,
    rating: 4.7,
    reviewCount: 1033,
    processor: "Snapdragon 8 Elite for Galaxy",
    ram: "12GB",
    ramGb: 12,
    storage: "256GB",
    storageGb: 256,
    display: '6.2" Dynamic AMOLED 2X 120Hz',
    battery: "4000mAh",
    batteryScore: 78,
    performance: "Compact flagship",
    performanceScore: 93,
    camera: "50MP + 12MP + 10MP",
    weight: "162g",
    weightGrams: 162,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Compact Android",
    pros: ["Compact and comfortable design", "Strong Samsung software features", "Fast day-to-day performance"],
    cons: ["Battery is only average", "Charging speeds trail some rivals"],
    summary: "A compact Galaxy flagship for buyers who want premium power in a smaller form factor.",
    imageLabel: "Official Samsung product image",
    tags: ["samsung", "galaxy", "android", "compact"],
  },
  {
    id: "smartphone-galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    category: "Smartphones",
    imageUrl:
      "https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-s25-ultra/images/galaxy-s25-ultra-features-highlights-galaxy-ai-a-start.jpg",
    price: 1299,
    rating: 4.8,
    reviewCount: 1184,
    processor: "Snapdragon 8 Elite for Galaxy",
    ram: "12GB",
    ramGb: 12,
    storage: "512GB",
    storageGb: 512,
    display: '6.9" Dynamic AMOLED 2X 120Hz',
    battery: "5000mAh",
    batteryScore: 91,
    performance: "Ultra flagship",
    performanceScore: 98,
    camera: "200MP + 50MP + 50MP + 12MP",
    weight: "232g",
    weightGrams: 232,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Zoom Camera",
    pros: ["Excellent zoom versatility", "Large bright display", "Premium multitasking tools"],
    cons: ["Large and heavy", "High launch price"],
    summary: "Samsung’s flagship pick for power users who want screen size, zoom range, and top-tier performance.",
    imageLabel: "Official Samsung product image",
    tags: ["samsung", "galaxy", "ultra", "camera"],
    featured: true,
  },
  {
    id: "smartphone-galaxy-z-fold6",
    name: "Samsung Galaxy Z Fold6",
    category: "Smartphones",
    imageUrl:
      "https://image-us.samsung.com/us/smartphones/galaxy-z-fold6/images/galaxy-z-fold6-features-kv.jpg",
    price: 1899,
    rating: 4.5,
    reviewCount: 611,
    processor: "Snapdragon 8 Gen 3 for Galaxy",
    ram: "12GB",
    ramGb: 12,
    storage: "512GB",
    storageGb: 512,
    display: '7.6" Foldable AMOLED 120Hz',
    battery: "4400mAh",
    batteryScore: 74,
    performance: "Foldable productivity flagship",
    performanceScore: 94,
    camera: "50MP + 12MP + 10MP",
    weight: "239g",
    weightGrams: 239,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Multitasking Android",
    pros: ["Large multitasking canvas", "Premium hinge and build", "Strong software for split-screen use"],
    cons: ["Very expensive", "Battery life is good, not great"],
    summary: "A premium foldable built for productivity, reading, and multi-app workflows on the go.",
    imageLabel: "Official Samsung product image",
    tags: ["samsung", "galaxy", "foldable", "productivity"],
  },
]

const brandedTablets: Product[] = [
  {
    id: "tablet-ipad-air-m4",
    name: "iPad Air M4",
    category: "Tablets",
    imageUrl:
      "https://www.apple.com/v/ipad-air/ah/images/meta/ipad-air_overview__bc2fd15uec0y_og.png",
    price: 599,
    rating: 4.8,
    reviewCount: 702,
    processor: "Apple M4",
    ram: "8GB",
    ramGb: 8,
    storage: "128GB",
    storageGb: 128,
    display: '11" Liquid Retina',
    battery: "Up to 10 hours",
    batteryScore: 80,
    performance: "Balanced creative tablet",
    performanceScore: 92,
    camera: "12MP rear + 12MP Center Stage front",
    weight: "462g",
    weightGrams: 462,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Tablet Value",
    pros: ["Fast M4 performance", "Excellent accessory support", "Strong app ecosystem"],
    cons: ["Base storage is modest", "Display is not OLED"],
    summary: "A versatile iPad that balances performance, portability, and long-term software support.",
    imageLabel: "Official Apple product image",
    tags: ["ipad", "apple", "tablet", "value"],
    featured: true,
  },
  {
    id: "tablet-ipad-pro-m5",
    name: "iPad Pro M5",
    category: "Tablets",
    imageUrl:
      "https://www.apple.com/v/ipad-pro/aw/images/meta/ipad-pro_overview__bu4cql27diaa_og.png",
    price: 999,
    rating: 4.9,
    reviewCount: 488,
    processor: "Apple M5",
    ram: "16GB",
    ramGb: 16,
    storage: "256GB",
    storageGb: 256,
    display: '11" Ultra Retina XDR',
    battery: "Up to 10 hours",
    batteryScore: 80,
    performance: "Pro creative tablet",
    performanceScore: 98,
    camera: "12MP rear + LiDAR + 12MP front",
    weight: "444g",
    weightGrams: 444,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Premium Tablet",
    pros: ["Outstanding display quality", "Top-end chip performance", "Excellent stylus and keyboard support"],
    cons: ["Expensive once accessories are included", "iPadOS still caps some pro workflows"],
    summary: "Apple’s premium tablet for editing, drawing, media, and demanding multitasking.",
    imageLabel: "Official Apple product image",
    tags: ["ipad", "apple", "pro", "oled"],
  },
  {
    id: "tablet-lenovo-tab-plus",
    name: "Lenovo Tab Plus",
    category: "Tablets",
    imageUrl:
      "https://p2-ofp.static.pub//fes/cms/2024/04/02/ktc2e0nyhy9kgheh7b6sraf3t5lg78015342.png?height=584&width=584",
    price: 319,
    rating: 4.4,
    reviewCount: 589,
    processor: "Helio G99",
    ram: "8GB",
    ramGb: 8,
    storage: "128GB",
    storageGb: 128,
    display: '11.5" 2K LCD 90Hz',
    battery: "8600mAh",
    batteryScore: 87,
    performance: "Entertainment tablet",
    performanceScore: 68,
    camera: "8MP rear + 8MP front",
    weight: "650g",
    weightGrams: 650,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best for Streaming",
    pros: ["Great built-in speakers", "Useful kickstand design", "Strong value pricing"],
    cons: ["Midrange performance only", "Heavier than slimmer tablets"],
    summary: "A value-focused Lenovo tablet designed around media consumption and casual family use.",
    imageLabel: "Official Lenovo product image",
    tags: ["lenovo", "tablet", "entertainment", "value"],
  },
  {
    id: "tablet-lenovo-idea-tab-pro",
    name: "Lenovo Idea Tab Pro",
    category: "Tablets",
    imageUrl:
      "https://p1-ofp.static.pub//fes/cms/2025/05/29/sfw34ky2o0jalxwtvnr9q7t0n7kk3v351995.png?height=584&width=584",
    price: 429,
    rating: 4.5,
    reviewCount: 344,
    processor: "MediaTek Dimensity 8300",
    ram: "8GB",
    ramGb: 8,
    storage: "256GB",
    storageGb: 256,
    display: '13" 3K LCD 144Hz',
    battery: "10200mAh",
    batteryScore: 93,
    performance: "Large-screen productivity tablet",
    performanceScore: 81,
    camera: "13MP rear + 8MP front",
    weight: "615g",
    weightGrams: 615,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Big-Screen Android Tablet",
    pros: ["Large crisp display", "Generous battery capacity", "Useful pen and keyboard support"],
    cons: ["LCD instead of OLED", "Accessory ecosystem is smaller than Apple’s"],
    summary: "A larger Lenovo tablet for study, entertainment, and light productivity on Android.",
    imageLabel: "Official Lenovo product image",
    tags: ["lenovo", "tablet", "android", "productivity"],
  },
]

const brandedSmartwatches: Product[] = [
  {
    id: "watch-garmin-vivoactive-6",
    name: "Garmin vivoactive 6",
    category: "Smartwatches",
    imageUrl:
      "https://res.garmin.com/en/products/010-02985-04/v/cf-lg.jpg",
    price: 299,
    rating: 4.7,
    reviewCount: 431,
    processor: "Garmin wellness platform",
    ram: "2GB",
    ramGb: 2,
    storage: "8GB",
    storageGb: 8,
    display: '1.2" AMOLED',
    battery: "Up to 11 days",
    batteryScore: 94,
    performance: "Wellness-first smartwatch",
    performanceScore: 77,
    camera: "No camera",
    weight: "36g",
    weightGrams: 36,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Wellness Tracking",
    pros: ["Excellent battery life", "Strong fitness and wellness metrics", "Comfortable lightweight fit"],
    cons: ["App ecosystem is limited", "Smart features are more basic than Wear OS"],
    summary: "A health-focused Garmin watch with strong battery life and dependable daily tracking.",
    imageLabel: "Official Garmin product image",
    tags: ["garmin", "smartwatch", "fitness", "battery"],
    featured: true,
  },
  {
    id: "watch-garmin-forerunner-265",
    name: "Garmin Forerunner 265",
    category: "Smartwatches",
    imageUrl:
      "https://res.garmin.com/en/products/010-02810-01/v/cf-lg.jpg",
    price: 449,
    rating: 4.8,
    reviewCount: 522,
    processor: "Garmin training platform",
    ram: "2GB",
    ramGb: 2,
    storage: "8GB",
    storageGb: 8,
    display: '1.3" AMOLED',
    battery: "Up to 13 days",
    batteryScore: 96,
    performance: "Runner-focused smartwatch",
    performanceScore: 84,
    camera: "No camera",
    weight: "47g",
    weightGrams: 47,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best for Runners",
    pros: ["Excellent training insights", "Bright AMOLED display", "Very good GPS accuracy"],
    cons: ["Higher price than casual fitness watches", "Music and smart features are secondary"],
    summary: "A training-oriented Garmin built for runners who care about recovery, pace, and endurance tracking.",
    imageLabel: "Official Garmin product image",
    tags: ["garmin", "running", "gps", "smartwatch"],
  },
  {
    id: "watch-xiaomi-watch-s4",
    name: "Xiaomi Watch S4",
    category: "Smartwatches",
    imageUrl:
      "https://i02.appmifile.com/mi-com-product/fly-birds/xiaomi-watch-s4/pc/83b9bf1fc1dd85c8511cdf069f16577a.jpg",
    price: 159,
    rating: 4.4,
    reviewCount: 613,
    processor: "Xiaomi HyperOS wearable platform",
    ram: "2GB",
    ramGb: 2,
    storage: "32GB",
    storageGb: 32,
    display: '1.43" AMOLED',
    battery: "Up to 15 days",
    batteryScore: 97,
    performance: "Feature-rich value smartwatch",
    performanceScore: 71,
    camera: "No camera",
    weight: "44g",
    weightGrams: 44,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Battery Value",
    pros: ["Long battery life", "Premium-looking design", "Good value feature set"],
    cons: ["Best experience is inside Xiaomi ecosystem", "Third-party apps are limited"],
    summary: "A strong-value smartwatch with stylish hardware and battery-first appeal.",
    imageLabel: "Official Xiaomi product image",
    tags: ["xiaomi", "smartwatch", "battery", "value"],
  },
  {
    id: "watch-xiaomi-watch-s4-41mm",
    name: "Xiaomi Watch S4 41mm",
    category: "Smartwatches",
    imageUrl:
      "https://i02.appmifile.com/mi-com-product/fly-birds/xiaomi-watch-s4-41mm/pc/5b4e6b0b56eb587f2453da9226acd67a.jpg",
    price: 179,
    rating: 4.5,
    reviewCount: 284,
    processor: "Xiaomi HyperOS wearable platform",
    ram: "2GB",
    ramGb: 2,
    storage: "32GB",
    storageGb: 32,
    display: '1.32" AMOLED',
    battery: "Up to 8 days",
    batteryScore: 76,
    performance: "Compact premium smartwatch",
    performanceScore: 70,
    camera: "No camera",
    weight: "32g",
    weightGrams: 32,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Small Wrist Fit",
    pros: ["Compact and elegant design", "Bright AMOLED display", "Useful safety features"],
    cons: ["Shorter battery than larger siblings", "Smart features depend on phone ecosystem"],
    summary: "A smaller Xiaomi watch for buyers who want comfort, style, and everyday health tracking.",
    imageLabel: "Official Xiaomi product image",
    tags: ["xiaomi", "smartwatch", "compact", "amoled"],
  },
]

const skyworthDisplays: Product[] = [
  {
    id: "display-skyworth-google-tv-55",
    name: 'Skyworth 55" 4K Google TV',
    category: "TVs/Monitors",
    imageUrl:
      "https://skyworth-tv.oss-cn-shenzhen.aliyuncs.com/upload/image/201909/20190918002145540.jpg",
    price: 499,
    rating: 4.3,
    reviewCount: 298,
    processor: "Skyworth smart TV platform",
    ram: "3GB",
    ramGb: 3,
    storage: "32GB",
    storageGb: 32,
    display: '55" 4K LED 60Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Affordable smart TV",
    performanceScore: 68,
    camera: "N/A",
    weight: "11.8kg",
    weightGrams: 11800,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Budget Living Room TV",
    pros: ["Affordable 4K entry point", "Google TV convenience", "Slim modern look"],
    cons: ["HDR impact is limited", "60Hz panel only"],
    summary: "A value Skyworth TV for streaming, casual console play, and everyday family viewing.",
    imageLabel: "Official Skyworth product image",
    tags: ["skyworth", "tv", "4k", "google-tv"],
    featured: true,
  },
  {
    id: "display-skyworth-qled-65",
    name: 'Skyworth 65" QLED TV',
    category: "TVs/Monitors",
    imageUrl:
      "https://skyworth-tv.oss-cn-shenzhen.aliyuncs.com/upload/image/201909/20190918002145540.jpg",
    price: 799,
    rating: 4.5,
    reviewCount: 184,
    processor: "Skyworth smart TV platform",
    ram: "3GB",
    ramGb: 3,
    storage: "32GB",
    storageGb: 32,
    display: '65" 4K QLED 120Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Large-screen entertainment TV",
    performanceScore: 79,
    camera: "N/A",
    weight: "17.6kg",
    weightGrams: 17600,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Big-Screen Value",
    pros: ["Large immersive panel", "Better color volume than standard LED", "Good value at this size"],
    cons: ["Black levels are only decent", "UI performance can vary by region"],
    summary: "A larger Skyworth TV aimed at movie nights, sports, and family-room streaming.",
    imageLabel: "Official Skyworth product image",
    tags: ["skyworth", "tv", "qled", "large-screen"],
  },
  {
    id: "display-skyworth-oled-55",
    name: 'Skyworth 55" OLED TV',
    category: "TVs/Monitors",
    imageUrl:
      "https://skyworth-tv.oss-cn-shenzhen.aliyuncs.com/upload/image/201909/20190918002145540.jpg",
    price: 1199,
    rating: 4.6,
    reviewCount: 122,
    processor: "Skyworth premium picture engine",
    ram: "4GB",
    ramGb: 4,
    storage: "64GB",
    storageGb: 64,
    display: '55" 4K OLED 120Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Premium cinematic TV",
    performanceScore: 86,
    camera: "N/A",
    weight: "14.9kg",
    weightGrams: 14900,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Picture Quality",
    pros: ["Excellent contrast", "Strong movie experience", "Better motion and gaming support"],
    cons: ["Costs more than LED models", "Potential static-image care needed"],
    summary: "A premium Skyworth OLED for home theater buyers who care about contrast and cinematic depth.",
    imageLabel: "Official Skyworth product image",
    tags: ["skyworth", "tv", "oled", "cinema"],
  },
  {
    id: "display-skyworth-mini-led-75",
    name: 'Skyworth 75" Mini-LED TV',
    category: "TVs/Monitors",
    imageUrl:
      "https://skyworth-tv.oss-cn-shenzhen.aliyuncs.com/upload/image/201909/20190918002145540.jpg",
    price: 1499,
    rating: 4.5,
    reviewCount: 96,
    processor: "Skyworth premium picture engine",
    ram: "4GB",
    ramGb: 4,
    storage: "64GB",
    storageGb: 64,
    display: '75" 4K Mini-LED 144Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "High-end bright-room TV",
    performanceScore: 88,
    camera: "N/A",
    weight: "26.4kg",
    weightGrams: 26400,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Bright Room Screen",
    pros: ["Very large and bright panel", "Strong refresh rate for gaming", "Better HDR impact than standard LED"],
    cons: ["Huge footprint", "Premium pricing within the brand"],
    summary: "A larger Skyworth TV for buyers who want size, brightness, and smoother gaming support.",
    imageLabel: "Official Skyworth product image",
    tags: ["skyworth", "tv", "mini-led", "gaming"],
  },
]

const legacyProducts: Product[] = [
  {
    id: "smartphone-aether-x1",
    name: "Aether X1 Pro",
    category: "Smartphones",
    price: 999,
    rating: 4.8,
    reviewCount: 1248,
    processor: "Snapdragon 8 Elite",
    ram: "12GB",
    ramGb: 12,
    storage: "256GB",
    storageGb: 256,
    display: '6.7" AMOLED 120Hz',
    battery: "5100mAh",
    batteryScore: 92,
    performance: "Flagship",
    performanceScore: 98,
    camera: "50MP + 48MP + 12MP",
    weight: "198g",
    weightGrams: 198,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Overall",
    pros: ["Excellent camera consistency", "Bright outdoor display", "Fast wired and wireless charging"],
    cons: ["Premium price", "No charger in the box"],
    summary: "A polished flagship with balanced power, camera quality, and battery life.",
    imageLabel: "Titan silver phone",
    tags: ["flagship", "camera", "120hz"],
    featured: true,
  },
  {
    id: "smartphone-orbit-s9",
    name: "Orbit S9",
    category: "Smartphones",
    price: 849,
    rating: 4.7,
    reviewCount: 986,
    processor: "Tensor G5",
    ram: "12GB",
    ramGb: 12,
    storage: "256GB",
    storageGb: 256,
    display: '6.4" OLED 120Hz',
    battery: "4850mAh",
    batteryScore: 86,
    performance: "Advanced AI",
    performanceScore: 90,
    camera: "50MP + 48MP + 10MP",
    weight: "191g",
    weightGrams: 191,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best AI Features",
    pros: ["Useful on-device AI tools", "Strong photo processing", "Clean Android experience"],
    cons: ["Gaming thermals are average", "Charging is slower than rivals"],
    summary: "Ideal for buyers who care about photography, smart features, and a clean OS.",
    imageLabel: "Graphite phone",
    tags: ["android", "ai", "camera"],
  },
  {
    id: "smartphone-nova-lite",
    name: "Nova Lite 5G",
    category: "Smartphones",
    price: 449,
    rating: 4.5,
    reviewCount: 1734,
    processor: "Snapdragon 7s Gen 3",
    ram: "8GB",
    ramGb: 8,
    storage: "256GB",
    storageGb: 256,
    display: '6.6" OLED 120Hz',
    battery: "5200mAh",
    batteryScore: 94,
    performance: "Upper midrange",
    performanceScore: 82,
    camera: "50MP + 8MP + 2MP",
    weight: "187g",
    weightGrams: 187,
    warranty: "18 months",
    warrantyMonths: 18,
    bestFor: "Best Budget",
    pros: ["Great value for money", "Long-lasting battery", "Sharp display for the price"],
    cons: ["Secondary cameras are weak", "Plastic frame"],
    summary: "A budget-friendly phone that still feels fast and modern for daily use.",
    imageLabel: "Blue budget phone",
    tags: ["budget", "battery", "value"],
    featured: true,
  },
  {
    id: "smartphone-volt-max",
    name: "Volt Max Ultra",
    category: "Smartphones",
    price: 1199,
    rating: 4.7,
    reviewCount: 763,
    processor: "A19 Pro",
    ram: "8GB",
    ramGb: 8,
    storage: "512GB",
    storageGb: 512,
    display: '6.9" LTPO OLED 120Hz',
    battery: "4680mAh",
    batteryScore: 84,
    performance: "Top-tier",
    performanceScore: 99,
    camera: "48MP + 48MP + 12MP",
    weight: "221g",
    weightGrams: 221,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Video",
    pros: ["Outstanding chip performance", "Class-leading video quality", "Premium build"],
    cons: ["Expensive upgrades", "Heavier than most phones"],
    summary: "A premium large-screen choice for creators and power users.",
    imageLabel: "Champagne gold phone",
    tags: ["ios", "video", "premium"],
  },
  {
    id: "smartphone-pulse-fold",
    name: "Pulse Fold Air",
    category: "Smartphones",
    price: 1399,
    rating: 4.4,
    reviewCount: 402,
    processor: "Snapdragon 8 Elite",
    ram: "12GB",
    ramGb: 12,
    storage: "512GB",
    storageGb: 512,
    display: '7.8" Foldable AMOLED 120Hz',
    battery: "4600mAh",
    batteryScore: 80,
    performance: "Flagship foldable",
    performanceScore: 95,
    camera: "50MP + 12MP + 10MP",
    weight: "239g",
    weightGrams: 239,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Multitasking",
    pros: ["Large immersive inner display", "Strong multitasking software", "Premium hinge feel"],
    cons: ["Very expensive", "Battery is average for the size"],
    summary: "A foldable built for productivity, reading, and split-screen workflows.",
    imageLabel: "Foldable phone open",
    tags: ["foldable", "productivity", "premium"],
  },
  {
    id: "smartphone-rally-gt",
    name: "Rally GT Gaming Phone",
    category: "Smartphones",
    price: 799,
    rating: 4.6,
    reviewCount: 689,
    processor: "Dimensity 9400",
    ram: "16GB",
    ramGb: 16,
    storage: "512GB",
    storageGb: 512,
    display: '6.8" AMOLED 165Hz',
    battery: "6000mAh",
    batteryScore: 98,
    performance: "Gaming flagship",
    performanceScore: 97,
    camera: "50MP + 13MP + 5MP",
    weight: "228g",
    weightGrams: 228,
    warranty: "18 months",
    warrantyMonths: 18,
    bestFor: "Best for Gaming",
    pros: ["Very high sustained performance", "Huge battery", "Responsive shoulder triggers"],
    cons: ["Bulky design", "Camera system is only decent"],
    summary: "A performance-first phone tuned for long gaming sessions and fast touch response.",
    imageLabel: "Angular gaming phone",
    tags: ["gaming", "battery", "performance"],
    featured: true,
  },
  {
    id: "laptop-zenbook-air",
    name: "Zenbook Air 14",
    category: "Laptops",
    price: 1299,
    rating: 4.8,
    reviewCount: 533,
    processor: "Intel Core Ultra 7 268V",
    ram: "16GB",
    ramGb: 16,
    storage: "1TB SSD",
    storageGb: 1024,
    display: '14" OLED 3K',
    battery: "18 hours",
    batteryScore: 89,
    performance: "Productivity premium",
    performanceScore: 88,
    camera: "1080p webcam",
    weight: "1.18kg",
    weightGrams: 1180,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Portability",
    pros: ["Very light and premium", "Excellent OLED panel", "Strong battery endurance"],
    cons: ["Limited ports", "Not meant for heavy gaming"],
    summary: "A thin-and-light laptop that feels premium without sacrificing battery life.",
    imageLabel: "Slim silver laptop",
    tags: ["portable", "oled", "work"],
    featured: true,
  },
  {
    id: "laptop-terra-pro-16",
    name: "Terra Pro 16",
    category: "Laptops",
    price: 1899,
    rating: 4.7,
    reviewCount: 318,
    processor: "AMD Ryzen AI 9 HX 370",
    ram: "32GB",
    ramGb: 32,
    storage: "1TB SSD",
    storageGb: 1024,
    display: '16" Mini-LED 165Hz',
    battery: "11 hours",
    batteryScore: 70,
    performance: "Creator workstation",
    performanceScore: 95,
    camera: "1440p webcam",
    weight: "1.95kg",
    weightGrams: 1950,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best for Creators",
    pros: ["Strong multi-core performance", "Color-accurate display", "Generous RAM"],
    cons: ["Heavier chassis", "Fan noise under load"],
    summary: "A high-power laptop for editing, rendering, and multitasking-heavy workflows.",
    imageLabel: "Dark creator laptop",
    tags: ["creator", "mini-led", "workstation"],
  },
  {
    id: "laptop-summit-15",
    name: "Summit 15 Everyday",
    category: "Laptops",
    price: 899,
    rating: 4.4,
    reviewCount: 890,
    processor: "Intel Core 7 250H",
    ram: "16GB",
    ramGb: 16,
    storage: "512GB SSD",
    storageGb: 512,
    display: '15.3" IPS 120Hz',
    battery: "13 hours",
    batteryScore: 78,
    performance: "Mainstream",
    performanceScore: 76,
    camera: "1080p webcam",
    weight: "1.62kg",
    weightGrams: 1620,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Everyday Value",
    pros: ["Good port selection", "Comfortable keyboard", "Fair price for the specs"],
    cons: ["Display contrast is average", "Speakers are only okay"],
    summary: "A balanced midrange laptop for students, work, and casual entertainment.",
    imageLabel: "Everyday clamshell laptop",
    tags: ["student", "value", "everyday"],
  },
  {
    id: "laptop-vector-g7",
    name: "Vector G7",
    category: "Laptops",
    price: 2199,
    rating: 4.6,
    reviewCount: 271,
    processor: "Intel Core Ultra 9 285H + RTX 5080",
    ram: "32GB",
    ramGb: 32,
    storage: "2TB SSD",
    storageGb: 2048,
    display: '16" QHD+ 240Hz',
    battery: "7 hours",
    batteryScore: 58,
    performance: "High-end gaming",
    performanceScore: 99,
    camera: "1080p webcam",
    weight: "2.32kg",
    weightGrams: 2320,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best for Gaming",
    pros: ["Outstanding gaming power", "Fast high-refresh display", "Plenty of storage"],
    cons: ["Shorter battery life", "Bulky charger"],
    summary: "A desktop-class gaming laptop for demanding AAA titles and esports.",
    imageLabel: "Gaming laptop with RGB",
    tags: ["gaming", "rtx", "240hz"],
  },
  {
    id: "laptop-orbit-13",
    name: "Orbit 13 Flex",
    category: "Laptops",
    price: 1099,
    rating: 4.5,
    reviewCount: 467,
    processor: "Snapdragon X Plus",
    ram: "16GB",
    ramGb: 16,
    storage: "512GB SSD",
    storageGb: 512,
    display: '13.5" Touch IPS',
    battery: "20 hours",
    batteryScore: 96,
    performance: "Always-on ultraportable",
    performanceScore: 74,
    camera: "1440p webcam",
    weight: "1.22kg",
    weightGrams: 1220,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Battery",
    pros: ["Exceptional battery life", "Quiet fanless feel", "Versatile touchscreen form factor"],
    cons: ["Some app compatibility caveats", "Not for heavy 3D workloads"],
    summary: "A long-endurance ultraportable that prioritizes mobility and simplicity.",
    imageLabel: "Convertible thin laptop",
    tags: ["battery", "portable", "2-in-1"],
  },
  {
    id: "laptop-studio-book",
    name: "Studio Book 17",
    category: "Laptops",
    price: 2499,
    rating: 4.7,
    reviewCount: 198,
    processor: "Apple M5 Pro",
    ram: "36GB",
    ramGb: 36,
    storage: "1TB SSD",
    storageGb: 1024,
    display: '17" Liquid Retina XDR',
    battery: "17 hours",
    batteryScore: 88,
    performance: "Pro creative",
    performanceScore: 97,
    camera: "12MP Center Stage",
    weight: "2.05kg",
    weightGrams: 2050,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Display",
    pros: ["Exceptional display quality", "Very strong sustained performance", "Quiet under load"],
    cons: ["High price", "Limited upgrade flexibility"],
    summary: "A premium workstation-class laptop with excellent display fidelity and battery balance.",
    imageLabel: "Large premium laptop",
    tags: ["display", "creative", "premium"],
  },
  {
    id: "tablet-canvas-13",
    name: "Canvas Tab 13",
    category: "Tablets",
    price: 999,
    rating: 4.8,
    reviewCount: 354,
    processor: "M4",
    ram: "8GB",
    ramGb: 8,
    storage: "256GB",
    storageGb: 256,
    display: '13" Tandem OLED',
    battery: "12 hours",
    batteryScore: 80,
    performance: "Creative flagship",
    performanceScore: 96,
    camera: "12MP rear + 12MP front",
    weight: "582g",
    weightGrams: 582,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best for Creatives",
    pros: ["Industry-leading display", "Excellent stylus response", "Thin and premium build"],
    cons: ["Accessories add a lot to the price", "iPadOS multitasking still has limits"],
    summary: "A premium tablet for sketching, editing, and content consumption.",
    imageLabel: "Large OLED tablet",
    tags: ["creative", "oled", "premium"],
    featured: true,
  },
  {
    id: "tablet-nimbus-11",
    name: "Nimbus 11",
    category: "Tablets",
    price: 649,
    rating: 4.6,
    reviewCount: 421,
    processor: "Tensor T3",
    ram: "8GB",
    ramGb: 8,
    storage: "128GB",
    storageGb: 128,
    display: '11" LCD 120Hz',
    battery: "13 hours",
    batteryScore: 84,
    performance: "Media focused",
    performanceScore: 78,
    camera: "13MP rear + 8MP front",
    weight: "503g",
    weightGrams: 503,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Entertainment",
    pros: ["Smooth 120Hz display", "Great speaker tuning", "Useful smart home dock mode"],
    cons: ["Performance is not top-tier", "Base storage is modest"],
    summary: "A friendly Android tablet aimed at streaming, browsing, and casual productivity.",
    imageLabel: "Slate media tablet",
    tags: ["media", "android", "120hz"],
  },
  {
    id: "tablet-verse-air",
    name: "Verse Air 10",
    category: "Tablets",
    price: 399,
    rating: 4.4,
    reviewCount: 867,
    processor: "Snapdragon 7 Gen 2",
    ram: "8GB",
    ramGb: 8,
    storage: "128GB",
    storageGb: 128,
    display: '10.9" IPS',
    battery: "14 hours",
    batteryScore: 88,
    performance: "Midrange tablet",
    performanceScore: 70,
    camera: "8MP rear + 8MP front",
    weight: "471g",
    weightGrams: 471,
    warranty: "18 months",
    warrantyMonths: 18,
    bestFor: "Best Budget Tablet",
    pros: ["Affordable and reliable", "Solid battery life", "Lightweight chassis"],
    cons: ["Average display brightness", "Accessories sold separately"],
    summary: "A value-first tablet that handles reading, web tasks, and family streaming well.",
    imageLabel: "Light blue tablet",
    tags: ["budget", "family", "value"],
  },
  {
    id: "tablet-workpad-pro",
    name: "WorkPad Pro 12",
    category: "Tablets",
    price: 799,
    rating: 4.5,
    reviewCount: 295,
    processor: "Intel Core Ultra 5 238V",
    ram: "16GB",
    ramGb: 16,
    storage: "512GB SSD",
    storageGb: 512,
    display: '12.6" OLED',
    battery: "10 hours",
    batteryScore: 68,
    performance: "Desktop-class tablet",
    performanceScore: 85,
    camera: "10MP rear + 5MP front",
    weight: "876g",
    weightGrams: 876,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Productivity",
    pros: ["Desktop apps support", "Useful keyboard cover", "Fast SSD storage"],
    cons: ["Heavier than mobile-first tablets", "Battery life trails rivals"],
    summary: "A hybrid tablet-laptop for users who need full desktop workflows on the go.",
    imageLabel: "Tablet with kickstand",
    tags: ["productivity", "windows", "hybrid"],
  },
  {
    id: "watch-apex-run",
    name: "Apex Run Watch",
    category: "Smartwatches",
    price: 349,
    rating: 4.7,
    reviewCount: 615,
    processor: "Apex S4",
    ram: "2GB",
    ramGb: 2,
    storage: "32GB",
    storageGb: 32,
    display: '1.4" AMOLED',
    battery: "7 days",
    batteryScore: 90,
    performance: "Fitness optimized",
    performanceScore: 80,
    camera: "No camera",
    weight: "37g",
    weightGrams: 37,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best for Fitness",
    pros: ["Excellent GPS accuracy", "Long battery life", "Light and comfortable"],
    cons: ["App ecosystem is smaller", "No LTE option"],
    summary: "A fitness-focused watch with strong training metrics and endurance.",
    imageLabel: "Sport smartwatch",
    tags: ["fitness", "gps", "battery"],
  },
  {
    id: "watch-lumen-classic",
    name: "Lumen Watch Classic",
    category: "Smartwatches",
    price: 429,
    rating: 4.6,
    reviewCount: 482,
    processor: "Wear X2",
    ram: "2GB",
    ramGb: 2,
    storage: "32GB",
    storageGb: 32,
    display: '1.5" AMOLED',
    battery: "2 days",
    batteryScore: 52,
    performance: "Smart assistant",
    performanceScore: 82,
    camera: "No camera",
    weight: "42g",
    weightGrams: 42,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Smart Features",
    pros: ["Strong app selection", "Bright stylish display", "Reliable voice assistant"],
    cons: ["Battery life is short", "Some health features require subscriptions"],
    summary: "A polished smartwatch for notifications, apps, and wrist-based convenience.",
    imageLabel: "Polished round watch",
    tags: ["smart", "apps", "amoled"],
  },
  {
    id: "watch-nord-eco",
    name: "Nord Eco Watch",
    category: "Smartwatches",
    price: 229,
    rating: 4.4,
    reviewCount: 928,
    processor: "NordFit 2",
    ram: "1GB",
    ramGb: 1,
    storage: "8GB",
    storageGb: 8,
    display: '1.32" AMOLED',
    battery: "10 days",
    batteryScore: 97,
    performance: "Health tracking",
    performanceScore: 68,
    camera: "No camera",
    weight: "31g",
    weightGrams: 31,
    warranty: "18 months",
    warrantyMonths: 18,
    bestFor: "Best Battery",
    pros: ["Excellent endurance", "Comfortable slim case", "Good everyday wellness tracking"],
    cons: ["Limited third-party apps", "Performance is basic"],
    summary: "A light and affordable watch built around comfort and long battery life.",
    imageLabel: "Minimal slim smartwatch",
    tags: ["battery", "value", "health"],
  },
  {
    id: "watch-orbit-kids",
    name: "Orbit Active Watch SE",
    category: "Smartwatches",
    price: 279,
    rating: 4.3,
    reviewCount: 301,
    processor: "Orbit Lite",
    ram: "1GB",
    ramGb: 1,
    storage: "16GB",
    storageGb: 16,
    display: '1.6" LCD',
    battery: "3 days",
    batteryScore: 66,
    performance: "Essential smartwatch",
    performanceScore: 64,
    camera: "No camera",
    weight: "29g",
    weightGrams: 29,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Entry-Level",
    pros: ["Affordable access to core smartwatch features", "Lightweight feel", "Simple setup"],
    cons: ["Lower-end display", "Fewer advanced sensors"],
    summary: "A simpler smartwatch for first-time buyers who want notifications and wellness basics.",
    imageLabel: "Compact smartwatch",
    tags: ["entry", "budget", "simple"],
  },
  {
    id: "earbuds-sonic-pro",
    name: "Sonic Pro Buds",
    category: "Earbuds",
    price: 249,
    rating: 4.7,
    reviewCount: 1262,
    processor: "Sonic Audio Core",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: "Companion app EQ",
    battery: "8h + 30h case",
    batteryScore: 88,
    performance: "Premium ANC",
    performanceScore: 86,
    camera: "N/A",
    weight: "5.3g per bud",
    weightGrams: 11,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Noise Cancelling",
    pros: ["Strong ANC performance", "Rich balanced sound", "Reliable call quality"],
    cons: ["Case is slightly bulky", "Premium pricing"],
    summary: "High-end earbuds tuned for commuting, calls, and polished everyday listening.",
    imageLabel: "Premium wireless earbuds",
    tags: ["anc", "audio", "premium"],
    featured: true,
  },
  {
    id: "earbuds-pulse-open",
    name: "Pulse Open Fit",
    category: "Earbuds",
    price: 179,
    rating: 4.5,
    reviewCount: 648,
    processor: "Pulse Wireless 3",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: "Open-ear design",
    battery: "9h + 24h case",
    batteryScore: 86,
    performance: "Workout friendly",
    performanceScore: 72,
    camera: "N/A",
    weight: "8.6g per bud",
    weightGrams: 17,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best for Workouts",
    pros: ["Comfortable open-ear fit", "Good stability while moving", "Awareness of surroundings"],
    cons: ["Less bass than sealed earbuds", "Sound leaks at high volume"],
    summary: "A comfortable open-ear set for exercise, walking, and all-day wear.",
    imageLabel: "Open-ear earbuds",
    tags: ["fitness", "open-ear", "comfort"],
  },
  {
    id: "earbuds-echo-max",
    name: "Echo Max Headphones",
    category: "Earbuds",
    price: 329,
    rating: 4.8,
    reviewCount: 857,
    processor: "Echo Sound Engine X",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: "Wear-detection controls",
    battery: "35 hours",
    batteryScore: 95,
    performance: "Audiophile wireless",
    performanceScore: 90,
    camera: "N/A",
    weight: "254g",
    weightGrams: 254,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Sound Quality",
    pros: ["Excellent tuning and detail", "Strong battery life", "Comfortable over-ear cushions"],
    cons: ["Larger to carry around", "Premium price"],
    summary: "Wireless over-ear headphones for buyers who prioritize audio quality and endurance.",
    imageLabel: "Over-ear headphones",
    tags: ["headphones", "audio", "battery"],
  },
  {
    id: "earbuds-breeze-mini",
    name: "Breeze Mini Buds",
    category: "Earbuds",
    price: 89,
    rating: 4.2,
    reviewCount: 1531,
    processor: "Breeze Chip 2",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: "Tap controls",
    battery: "6h + 20h case",
    batteryScore: 70,
    performance: "Budget audio",
    performanceScore: 60,
    camera: "N/A",
    weight: "4.1g per bud",
    weightGrams: 8,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Budget Audio",
    pros: ["Very affordable", "Compact case", "Simple pairing"],
    cons: ["ANC is limited", "Microphone quality is average"],
    summary: "An inexpensive everyday pair for podcasts, calls, and casual music listening.",
    imageLabel: "Compact earbuds case",
    tags: ["budget", "compact", "casual"],
  },
  {
    id: "camera-lumen-r6",
    name: "Lumen R6 Mirrorless",
    category: "Cameras",
    price: 1899,
    rating: 4.8,
    reviewCount: 244,
    processor: "Lumen Image X",
    ram: "N/A",
    ramGb: 0,
    storage: "Dual SD slots",
    storageGb: 0,
    display: '3.2" articulating touchscreen',
    battery: "690 shots",
    batteryScore: 84,
    performance: "Hybrid creator",
    performanceScore: 92,
    camera: "33MP full-frame",
    weight: "588g",
    weightGrams: 588,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Hybrid Camera",
    pros: ["Excellent autofocus", "Strong photo and video balance", "Comfortable handling"],
    cons: ["Lenses can be expensive", "Menus take time to learn"],
    summary: "A versatile mirrorless camera for creators who shoot both stills and video.",
    imageLabel: "Mirrorless camera body",
    tags: ["mirrorless", "hybrid", "creator"],
    featured: true,
  },
  {
    id: "camera-nova-c100",
    name: "Nova C100 Compact",
    category: "Cameras",
    price: 799,
    rating: 4.5,
    reviewCount: 612,
    processor: "Nova Pixel 4",
    ram: "N/A",
    ramGb: 0,
    storage: "Single SD slot",
    storageGb: 0,
    display: '3" flip touchscreen',
    battery: "420 shots",
    batteryScore: 64,
    performance: "Pocket content creator",
    performanceScore: 74,
    camera: "1-inch 20MP sensor",
    weight: "304g",
    weightGrams: 304,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best for Vlogging",
    pros: ["Portable and travel-friendly", "Simple flip screen", "Good autofocus for casual creators"],
    cons: ["Battery is average", "Limited zoom range"],
    summary: "A compact camera built for travel, casual vlogging, and social media capture.",
    imageLabel: "Compact vlogging camera",
    tags: ["vlogging", "travel", "compact"],
  },
  {
    id: "camera-terra-sport",
    name: "Terra Sport Action Cam",
    category: "Cameras",
    price: 399,
    rating: 4.4,
    reviewCount: 1043,
    processor: "Terra Stabilize 2",
    ram: "N/A",
    ramGb: 0,
    storage: "microSD",
    storageGb: 0,
    display: '2.1" rear display',
    battery: "140 minutes",
    batteryScore: 60,
    performance: "Adventure capture",
    performanceScore: 68,
    camera: "5.3K action camera",
    weight: "154g",
    weightGrams: 154,
    warranty: "18 months",
    warrantyMonths: 18,
    bestFor: "Best for Action",
    pros: ["Very durable", "Strong stabilization", "Easy mounting system"],
    cons: ["Low-light quality is limited", "Gets warm at highest resolutions"],
    summary: "A rugged action camera for biking, hiking, travel, and point-of-view shooting.",
    imageLabel: "Action camera",
    tags: ["action", "rugged", "travel"],
  },
  {
    id: "camera-atelier-50",
    name: "Atelier 50 Classic",
    category: "Cameras",
    price: 2499,
    rating: 4.7,
    reviewCount: 155,
    processor: "Atelier Color Engine",
    ram: "N/A",
    ramGb: 0,
    storage: "Dual CFexpress",
    storageGb: 0,
    display: '3.1" tilting LCD',
    battery: "720 shots",
    batteryScore: 86,
    performance: "Photography-first",
    performanceScore: 88,
    camera: "40MP APS-C",
    weight: "521g",
    weightGrams: 521,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best for Street Photography",
    pros: ["Beautiful color rendering", "Tactile manual controls", "Compact for enthusiasts"],
    cons: ["Video features are not the main focus", "Premium lens ecosystem"],
    summary: "A photography-focused camera with tactile controls and strong image character.",
    imageLabel: "Retro mirrorless camera",
    tags: ["photography", "street", "retro"],
  },
  {
    id: "console-arcade-x",
    name: "Arcade X",
    category: "Gaming Consoles",
    price: 499,
    rating: 4.8,
    reviewCount: 2140,
    processor: "Zen 5 + RDNA 4",
    ram: "16GB",
    ramGb: 16,
    storage: "1TB SSD",
    storageGb: 1024,
    display: "4K 120Hz output",
    battery: "Plug-in",
    batteryScore: 0,
    performance: "4K flagship console",
    performanceScore: 96,
    camera: "N/A",
    weight: "4.3kg",
    weightGrams: 4300,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Performance Console",
    pros: ["Excellent performance", "Strong first-party lineup", "Quick resume features"],
    cons: ["Large footprint", "Storage fills up fast with big games"],
    summary: "A high-performance home console for 4K gaming and fast load times.",
    imageLabel: "White home console",
    tags: ["console", "4k", "performance"],
    featured: true,
  },
  {
    id: "console-playbox-slim",
    name: "PlayBox Slim",
    category: "Gaming Consoles",
    price: 449,
    rating: 4.7,
    reviewCount: 1982,
    processor: "Zen 4 + RDNA 3.5",
    ram: "16GB",
    ramGb: 16,
    storage: "1TB SSD",
    storageGb: 1024,
    display: "4K 120Hz output",
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Premium console",
    performanceScore: 92,
    camera: "N/A",
    weight: "3.2kg",
    weightGrams: 3200,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Exclusive Games",
    pros: ["Excellent controller feedback", "Strong exclusive catalog", "Slim redesign saves space"],
    cons: ["Paid online service adds cost", "Expandable storage is pricey"],
    summary: "A polished living-room console with strong exclusives and premium controller features.",
    imageLabel: "Slim black console",
    tags: ["console", "exclusive", "living-room"],
  },
  {
    id: "console-pixel-portable",
    name: "Pixel Portable OLED",
    category: "Gaming Consoles",
    price: 349,
    rating: 4.6,
    reviewCount: 1756,
    processor: "Custom Tegra X2",
    ram: "8GB",
    ramGb: 8,
    storage: "128GB",
    storageGb: 128,
    display: '7.8" OLED 90Hz',
    battery: "6 to 8 hours",
    batteryScore: 72,
    performance: "Hybrid portable",
    performanceScore: 70,
    camera: "N/A",
    weight: "426g",
    weightGrams: 426,
    warranty: "12 months",
    warrantyMonths: 12,
    bestFor: "Best Handheld Flexibility",
    pros: ["Portable and dockable", "Vibrant OLED display", "Family-friendly library"],
    cons: ["Less powerful than home consoles", "Battery varies by game"],
    summary: "A hybrid console designed for flexible handheld and TV play.",
    imageLabel: "Portable OLED console",
    tags: ["portable", "oled", "family"],
  },
  {
    id: "console-handheld-core",
    name: "Handheld Core 2",
    category: "Gaming Consoles",
    price: 699,
    rating: 4.5,
    reviewCount: 624,
    processor: "Ryzen Z2 Extreme",
    ram: "24GB",
    ramGb: 24,
    storage: "1TB SSD",
    storageGb: 1024,
    display: '8" IPS 144Hz',
    battery: "2 to 5 hours",
    batteryScore: 44,
    performance: "PC handheld",
    performanceScore: 88,
    camera: "N/A",
    weight: "714g",
    weightGrams: 714,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best PC Library Access",
    pros: ["Runs a broad PC game library", "High-refresh screen", "Strong emulation and tinkering potential"],
    cons: ["Heavy to hold for long sessions", "Battery life is modest"],
    summary: "A handheld gaming PC for buyers who want desktop-style library access on the move.",
    imageLabel: "Handheld gaming PC",
    tags: ["handheld", "pc", "144hz"],
  },
  {
    id: "display-clarity-32",
    name: "ClarityView 32 4K",
    category: "TVs/Monitors",
    price: 799,
    rating: 4.7,
    reviewCount: 722,
    processor: "Display Control Hub",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: '32" 4K IPS 144Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Creator monitor",
    performanceScore: 84,
    camera: "N/A",
    weight: "7.1kg",
    weightGrams: 7100,
    warranty: "36 months",
    warrantyMonths: 36,
    bestFor: "Best 4K Productivity",
    pros: ["Sharp 4K panel", "Strong color coverage", "Good USB-C connectivity"],
    cons: ["HDR is limited", "Stand adjustment could be better"],
    summary: "A crisp 4K monitor that balances productivity, creative work, and smooth refresh rates.",
    imageLabel: "32-inch monitor",
    tags: ["4k", "monitor", "creator"],
    featured: true,
  },
  {
    id: "display-ember-oled",
    name: "Ember OLED 55",
    category: "TVs/Monitors",
    price: 1499,
    rating: 4.8,
    reviewCount: 531,
    processor: "Vision AI XR",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: '55" OLED 120Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Home theater premium",
    performanceScore: 90,
    camera: "N/A",
    weight: "16.8kg",
    weightGrams: 16800,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Home Theater",
    pros: ["Excellent contrast and blacks", "Strong gaming support", "Premium picture processing"],
    cons: ["More expensive than mini-LED", "Potential burn-in risk for static content"],
    summary: "A premium OLED TV for movie nights, console gaming, and cinematic picture quality.",
    imageLabel: "Large OLED TV",
    tags: ["oled", "tv", "cinema"],
  },
  {
    id: "display-strike-27",
    name: "Strike 27 QHD",
    category: "TVs/Monitors",
    price: 429,
    rating: 4.6,
    reviewCount: 1198,
    processor: "Game Sync Engine",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: '27" QHD 240Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Competitive gaming monitor",
    performanceScore: 88,
    camera: "N/A",
    weight: "5.8kg",
    weightGrams: 5800,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best for Esports",
    pros: ["Very fast refresh rate", "Good motion clarity", "Strong value for competitive players"],
    cons: ["Speakers are weak", "Not ideal for HDR movies"],
    summary: "A gaming-focused monitor tuned for fast-paced competitive titles.",
    imageLabel: "QHD gaming monitor",
    tags: ["gaming", "240hz", "esports"],
  },
  {
    id: "display-slate-mini-led",
    name: "Slate Mini LED 65",
    category: "TVs/Monitors",
    price: 1199,
    rating: 4.5,
    reviewCount: 443,
    processor: "Quantum Vision Pro",
    ram: "N/A",
    ramGb: 0,
    storage: "N/A",
    storageGb: 0,
    display: '65" Mini-LED 144Hz',
    battery: "Plug-in",
    batteryScore: 0,
    performance: "Bright living-room TV",
    performanceScore: 86,
    camera: "N/A",
    weight: "19.6kg",
    weightGrams: 19600,
    warranty: "24 months",
    warrantyMonths: 24,
    bestFor: "Best Bright Room TV",
    pros: ["Very bright panel", "Good gaming feature support", "Large screen value"],
    cons: ["Blooming is still visible at times", "UI can feel busy"],
    summary: "A bright, large-screen TV that works well in shared living rooms and daytime spaces.",
    imageLabel: "Bright 65-inch TV",
    tags: ["mini-led", "bright-room", "tv"],
  },
]

const replacedCategories = new Set([
  "Smartphones",
  "Tablets",
  "Smartwatches",
  "TVs/Monitors",
])

export const products: Product[] = [
  ...brandedSmartphones,
  ...legacyProducts.filter((product) => !replacedCategories.has(product.category)),
  ...brandedTablets,
  ...brandedSmartwatches,
  ...skyworthDisplays,
]

export const productMap = Object.fromEntries(
  products.map((product) => [product.id, product])
)
